version: '3.8'

services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
      - ./:/var/www/html/wp-content/plugins/sync-manager
    user: "${PUID}:${PGID}"

  wpcli:
    depends_on:
      - wordpress
    image: wordpress:cli
    volumes:
      - wordpress_data:/var/www/html
    user: xfs
    entrypoint: wp
#    command: >
#      ash -c 'sleep 10 &&
#      wp core install --url="localhost:8000" --title="Local WordPress" --admin_user="admin" --admin_password="admin" --admin_email="admin@example.com" &&
#      wp user create admin admin@example.com --role=administrator --user_pass=admin'
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WP_DEBUG: true

volumes:
  db_data: { }
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/wordpress
